### ISSUE TITLE
GET https://grtp.co/v1/api.js net::ERR_INSECURE_RESPONSE

### ISSUE THREAD

**Issue by e9t** [gratipay/grtp.co#104]
My Gratipay widget suddenly disappeared, and I found the following error in my Chrome console:

    GET https://grtp.co/v1/api.js net::ERR_INSECURE_RESPONSE

So I tried accessed https://grtp.co/v1/api.js directly, and found a "Your connection is not private".
Has there been configurations with the Gratipay certificate recently, or might this a temporary or local issue?

**Comment by whit537** [comment]
@e9t Thanks for the report. I'm not able to reproduce the "Your connection is not private" message in Chrome 44.0.2403.130. Perhaps this is parallel to https://github.com/gratipay/gratipay.com/issues/3278?

**Comment by e9t** [comment]
Yes, I believe that's the same issue!
Since my widget is displaying properly now, and you already have a duplicate issue, I'll close this one. Thanks for the reply.

**Comment by whit537** [comment]
Cool. Sorry for the trouble. :-/
