### ISSUE TITLE
Upgrade to Ubuntu 14.04 LTS

### ISSUE THREAD

**Issue by techtonik** [gratipay/grtp.co#106]
We are running Ubuntu 12.04 on grtp.co droplet, which is probably the reason we still use Node 0.10.28. And the latest Gulp version requires Node 0.12+ https://travis-ci.org/gratipay/grtp.co/builds/89163317#L90

https://www.digitalocean.com/community/tutorials/how-to-upgrade-ubuntu-12-04-lts-to-ubuntu-14-04-lts

**Comment by whit537** [comment]
@techtonik I'll invite you to our Digital Ocean team. Can you email me at chad@zetaweb.com (or post here) with the email address you'd like me to use?

**Comment by techtonik** [comment]
@whit537 techtonik@gmail.com will do.

**Comment by whit537** [comment]
Invite sent!

**Comment by techtonik** [comment]
https://www.youtube.com/watch?v=M-ThqlqOvzY :battery:

**Comment by techtonik** [comment]
I don't see a way to make switch to new version without downtime without paying for the extra node, so it will take a while.

**Comment by techtonik** [comment]
Taking down the server..

**Comment by techtonik** [comment]
Taking snapshot..

**Comment by techtonik** [comment]
Connection restored..

**Comment by techtonik** [comment]
Hit this problem with upgrade https://www.digitalocean.com/community/questions/update-on-ubuntu-12-10-server-failing-not-found

**Comment by techtonik** [comment]
This helped https://askubuntu.com/questions/91815/how-to-install-software-or-upgrade-from-an-old-unsupported-release

**Comment by techtonik** [comment]
vimrc config is different from default.

nginx.cong is also different:
```
--- /etc/nginx/nginx.conf       2013-11-28 02:54:57.347202913 +0000
+++ /etc/nginx/nginx.conf.dpkg-new      2013-05-09 03:20:27.000000000 +0000
@@ -1,6 +1,6 @@
 user www-data;
 worker_processes 4;
-pid /var/run/nginx.pid;
+pid /run/nginx.pid;

 events {
        worker_connections 768;
@@ -38,15 +38,14 @@
        ##

        gzip on;
-       #gzip_disable "msie6";
+       gzip_disable "msie6";

-       gzip_vary on;
-       gzip_min_length 500;
-       gzip_proxied any;
-       gzip_comp_level 2;
+       # gzip_vary on;
+       # gzip_proxied any;
+       # gzip_comp_level 6;
        # gzip_buffers 16 8k;
        # gzip_http_version 1.1;
-       gzip_types text/plain text/css application/json application/x-javascript text/xml application/xml application/xml+rss text/javascript;
+       # gzip_types text/plain text/css application/json application/x-javascript text/xml application/xml application/xml+rss text/javascript;

        ##
        # nginx-naxsi config
```

**Comment by techtonik** [comment]
Why do we have disable `gzip_vary on`? @rummik ? For now I am putting it back to original Ubuntu version.

**Comment by techtonik** [comment]
Restarted..

**Comment by techtonik** [comment]
```
# lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 13.10
Release:        13.10
Codename:       saucy
```
Well... Seems like the process needs to be repeated.

**Comment by techtonik** [comment]
Changing kernel from control panel..

**Comment by techtonik** [comment]
Rebooted..

**Comment by techtonik** [comment]
```
# uname -ri
3.11.0-26-generic i686
```

**Comment by techtonik** [comment]
Disabled password authentication for root as prompted.

**Comment by techtonik** [comment]
Upgraded to Ubuntu 14.04.3 LTS (GNU/Linux 3.13.0-67-generic i686). Wheew..

**Comment by whit537** [comment]
Yay! !m @techtonik :dancer:

**Comment by techtonik** [comment]
I will try to up it to 15.10 once I repeat the configuration on local node.

**Comment by rummik** [comment]
@techtonik Old workarounds for IE6.  The default should be fine now.

**Comment by techtonik** [comment]
@rummik yea, it always helps to have config changes commented with references to such bugs.

**Comment by rummik** [comment]
@techtonik Yeah.  I don't know what I was thinking at the time :P

**Comment by techtonik** [comment]
@rummik nobody thinks about comments are needed until somebody else tries to read the code. =)

**Comment by rummik** [comment]
@techtonik I think it was mostly because of how useless I thought making it work well in IE6 was xD

**Comment by techtonik** [comment]
Maybe it was not useless at that time. Sometimes it is just interesting to hack and it is impossible to resist. :walking:

**Comment by rummik** [comment]
I didn't really want it in there.  IE6 was part of the reqs at the time, and now it isn't
