### ISSUE TITLE
Composite shield with demand / progress per project

### ISSUE THREAD

**Issue by techtonik** [gratipay/grtp.co#135]
```
[            ] hours committed
[            ] funds raised
your min/optimal rate [   ][   ]
```

I know that hourly rates don't reflect actual time that we spent when working on software problems, and minimal income is a better way to solve this problem, but just to calculate how seriously open source is underfunded, it is good to let people who donate enter their own desired salary/hourly rate and calculate supply/demand there.

The truth that in market economy people who are learning need more money than professionals, and this is a reason why learning quality drops - nobody pays them to learn or working for this rate is non-sustainable.

`your min/optimal rate [   ]` is entered by people manually and saved either in cookie or on the site. Site saving allows to build an average hourly survival sum with 40 per week.

Actually why not to add this to user preferences if we are about people. How many paid hours do I want to spend per week? How much do I need monthly?

**Comment by techtonik** [comment]
Step one - what is the state of the art of embedding widgets in GitHub markdown in May 2016?

**Comment by mattbk** [comment]
This is what goals used to be (part of 2nd generation widgets). I'm not sure how much of that is still in Gratipay itself, but maybe it could be refactored along those lines.
