### ISSUE TITLE
Use a larger DH parameter

### ISSUE THREAD

**Issue by nashe** [gratipay/grtp.co#144]
We need to change the current Diffie-Hellman parameter we are using, in order to get a "A" grade on SSSLabs and close [H1-117458](https://hackerone.com/reports/117458) + [H1-131065](https://hackerone.com/reports/131065).

To generate a now group with the recommended size, just run `openssl dhparam -out dhparams.pem 2048` in `/etc/nginx/`. It will take some time.

_(I don't really know how we should handle these kind of security reports, since nothing is specified on the *how-to* and the related configuration file don't have to be in this repository. I guess that making one issue and mentioning @whit537 is not the worst way.)_

Tell me when it's done, so I can PR the related nginx configuration directive :-)

**Comment by whit537** [comment]
Like this?

```
root@grtp:~# cd /etc/nginx/
root@grtp:/etc/nginx# l
certs/   fastcgi.conf    koi-utf  mime.types  nginx.conf.dpkg-old  scgi_params       sites-enabled/  uwsgi_params
conf.d/  fastcgi_params  koi-win  nginx.conf  proxy_params         sites-available/  snippets/       win-utf
root@grtp:/etc/nginx# openssl dhparam -out dhparams.pem 2048
Generating DH parameters, 2048 bit long safe prime, generator 2
This is going to take a long time
............................................................+........................................................................................................................................................................................+.......................................................................................................+..........................................................................................
```

**Comment by nashe** [comment]
Yep 👍

**Comment by whit537** [comment]
> Tell me when it's done, so I can PR the related nginx configuration directive :-)

It's not done yet, but you can start the PR whenever, and we'll simply wait to deploy. :)

**Comment by whit537** [comment]
Erp ... it's done! 💃

**Comment by nashe** [comment]
FTR, everything is working as expected and [ssllabs is still giving us a B](https://www.ssllabs.com/ssltest/analyze.html?d=grtp.co&latest) but for one other issue. I'm taking a look at it.
