### ISSUE TITLE
The certificate chain is incomplete

### ISSUE THREAD

**Issue by nashe** [gratipay/grtp.co#146]
After fixing the DH group size issue, [ssllabs](https://www.ssllabs.com/ssltest/analyze.html?d=grtp.co&latest=yes) is still showing this error to us:

>  This server's certificate chain is incomplete. Grade capped to B. 

Pretty self-explaining and easy to fix. We don't only have to send our certificate, but the ones for all the intermediates CA too: we'll have to concatenate everything into one file and give it to nginx. Let' reach the A o/

@whit537 Maybe the complete certificate already exists. Can you give me the output of a `ls -alh /etc/nginx/certs/`, please?

**Comment by whit537** [comment]
```
root@grtp:~# ls -alh /etc/nginx/certs/
total 32K
drwx------ 2 root root  4.0K Mar 10  2015 .
drwxr-xr-x 7 root root  4.0K Jul 14 14:11 ..
-rw------- 1 root root  4.9K Jun 13  2013 bundle.pem
-rw-r--r-- 1  501 staff 2.7K Mar  9  2015 grtp.co.crt
-rw-r--r-- 1  501 staff 3.2K Mar  9  2015 grtp.co.key
-rw-r--r-- 1 root root  4.4K Mar 10  2015 old.tbz
root@grtp:~#
```

**Comment by nashe** [comment]
I'd go for:  
```
cp grtp.co.crt grtp.co.crt.old
wget https://startssl.com/certs/sca.server2.crt
cat sca.server2.crt >> grtp.co.crt
service nginx restart
``` 

I think it's the right intermediate certificate. Can't find the suggested one displayed in the ssllabs records on startssl's website and never used anything else than Let's Encrypt 😞 Or maybe it's in the .zip you got when creating the certificated.

**Comment by whit537** [comment]
```
root@grtp:~# cd /etc/nginx
root@grtp:/etc/nginx# cd certs
root@grtp:/etc/nginx/certs# l
bundle.pem  grtp.co.crt  grtp.co.key  old.tbz
root@grtp:/etc/nginx/certs# cp grtp.co.crt grtp.co.crt.bak
root@grtp:/etc/nginx/certs# wget https://startssl.com/certs/sca.server2.crt
--2016-07-14 16:03:42--  https://startssl.com/certs/sca.server2.crt
Resolving startssl.com (startssl.com)... 4.14.40.138
Connecting to startssl.com (startssl.com)|4.14.40.138|:443... connected.

HTTP request sent, awaiting response... 200 OK
Length: 2140 (2.1K) [application/x-x509-ca-cert]
Saving to: ‘sca.server2.crt’

100%[==========================================================================>] 2,140       --.-K/s   in 0s      

2016-07-14 16:03:42 (242 MB/s) - ‘sca.server2.crt’ saved [2140/2140]

root@grtp:/etc/nginx/certs# cat sca.server2.crt >> grtp.co.crt
root@grtp:/etc/nginx/certs# service nginx restart
nginx stop/waiting
nginx start/running, process 22976
root@grtp:/etc/nginx/certs#
```

**Comment by whit537** [comment]
Looks like that wasn't sufficient.

**Comment by nashe** [comment]
That would be too easy… Let's go for a `cp grtp.co.crt.old grtp.co.crt && service nginx reload` while I try to find the right one. The only website linking to the *supposed* correct file is https://ssl-tools.net/subjects/b9b2d56db021b36e42f627245806c4a9a6979aeb, but I'm not considering this as a good solution.

**Comment by whit537** [comment]
I logged back into StartSSL and have re-retrieved a ZIP file for NGINX. Configuring ...

**Comment by whit537** [comment]
Looks like that worked! :-)

https://www.ssllabs.com/ssltest/analyze.html?d=grtp.co

**Comment by whit537** [comment]
@nashe Can I let you follow up on H1?

**Comment by nashe** [comment]
Sure! Updating the Radar accordingly. Thanks!
