### ISSUE TITLE
widgets tab shows old widget example, should reference v2 js

### ISSUE THREAD

**Issue by simonmichael** [gratipay/grtp.co#155]
The examples at https://gratipay.com/~username/widgets/ should probably be updated to match https://github.com/gratipay/grtp.co#standard-widgets . (I replaced username with project name in my widget (`<script data-gratipay-username="hledger" data-gratipay-widget="button" src="//grtp.co/v1.js"></script>`) and got a link to `https://gratipay.com/undefined/` until I noticed the link to newer widget docs.)

**Comment by whit537** [comment]
Ping @mattbk. Didn't we attempt this at one point during recent widget work?

**Comment by mattbk** [comment]
I had it working at one point, but it was tossed as part of https://github.com/gratipay/grtp.co/pull/112.

**Comment by whit537** [comment]
Ah, okay. Still live then.
