### ISSUE TITLE
Make it so that you do no-account widgets

### ISSUE THREAD

**Issue by nobodxbodon** [gratipay/grtp.co#156]
Reticket from https://github.com/gratipay/gratipay.com/issues/879
Maybe @PeterDaveHello could add some clarifications as well?

**Comment by PeterDaveHello** [comment]
I think it's the feature request of badge of project and organization, not a normal account?

**Comment by mattbk** [comment]
This may be a holdover from when you could pledge to a person before they actually had an account. A widget in that case would be useful for supporting a third party who you are trying to convince to join, in order for that party to collect pledged donations.

Widgets are centered around projects at the moment: https://github.com/gratipay/grtp.co#examples. There is a v1.js in use as well in the wild that is still in place that shows ~user information.

I don't see the need for this.
