### ISSUE TITLE
URL in description needs to be updated

### ISSUE THREAD

**Issue by techtonik** [gratipay/grtp.co#158]
It is not HTTPS

**Comment by whit537** [comment]
Which description?

**Comment by techtonik** [comment]
This one:
![clipcrop](https://cloud.githubusercontent.com/assets/515889/21992463/9930b3b4-dc27-11e6-914c-77e7f3faa6a9.png)

**Comment by whit537** [comment]
Done! An actionable issue ... closed!

!m @techtonik 😃 💃

**Comment by whit537** [comment]
![screen shot 2017-01-16 at 3 16 29 pm](https://cloud.githubusercontent.com/assets/134455/21997725/c5e3a0ac-dbfe-11e6-8da6-be98ddc9bc61.png)
