### ISSUE TITLE
Let's Encrypt

### ISSUE THREAD

**Issue by techtonik** [gratipay/grtp.co#159]
Something strange happens with the current HTTPS certificate on my system for https://grtp.co

![clipcrop](https://cloud.githubusercontent.com/assets/515889/21966022/7f6395e2-db7c-11e6-9d1a-7bb54eabe9eb.png)

https://gratipay.com/ is ok.

What if we switch to Let's Encrypt instead?

**Comment by EdOverflow** [comment]
I would like to add the following to the discussion: https://www.feistyduck.com/bulletproof-tls-newsletter/issue_20_mozilla_and_wosign_comodo_sb_and_tc_certificates.html

**Comment by techtonik** [comment]
Not more actual after #173.

**Comment by mattbk** [comment]
Solved in https://github.com/gratipay/inside.gratipay.com/issues/1051#issuecomment-300207516.
