### ISSUE TITLE
Work with Shields to better reflect Gratipay terminology

### ISSUE THREAD

**Issue by mattbk** [gratipay/grtp.co#163]
- [x] "tips" is definitely outdated (should be receives). https://github.com/badges/shields/pull/1053
- [x] replace "team" with "project" by default. https://github.com/badges/shields/pull/1053
- [x] ~~fix [bug with projects receiving $0.00](https://github.com/gratipay/gratipay.com/issues/4328#issuecomment-278851522)~~ Someone else got it: https://github.com/badges/shields/issues/1005
- [x] get out of the "Miscellaneous" category and into a new "Funding" category if possible. badges/shields#1053
- ~~should there be a difference between user and project shields?~~
    - ~~will anyone be using this to show how much they give?~~
    - [not this time](https://github.com/gratipay/grtp.co/issues/163#issuecomment-321908548)

I'd like to see Shields become the de facto simple widget for Gratipay, and expand our current widget into an onboarding platform (as referenced in several places).

Notes:
Use `node server 8080` to start, otherwise throws an error unrelated to server starting.

**Comment by techtonik** [comment]
I need to rebase and merge my existing PRs first - https://github.com/badges/shields/pulls/techtonik

**Comment by mattbk** [comment]
More reason to focus on improving Shields: This is how people are finding Gratipay! https://github.com/gratipay/project-review/issues?utf8=%E2%9C%93&q=is%3Aissue%20shield%20OR%20badge

**Comment by mattbk** [comment]
> - [ ] should there be a difference between ~user and project shields?
    - will anyone be using this to show how much they give?

Thinking about reticketing this one.

**Comment by whit537** [comment]
> will anyone be using this to show how much they give?

I'd wait for demand.

**Comment by mattbk** [comment]
Up for Gratipay review at https://gratipay.slackarchive.io/gratipay/.

How do I :wave: down one of the folks who can merge this if it looks okay?

**Comment by mattbk** [comment]
Merged, waiting for deploy to close...

**Comment by mattbk** [comment]
Deployed.

![image](https://user-images.githubusercontent.com/3729038/30444228-cff1d846-9947-11e7-94ce-546134a5a743.png)

**Comment by mattbk** [comment]
Why is receiving different than https://gratipay.com/Gratipay/?
