### ISSUE TITLE
Get deployment back on track

### ISSUE THREAD

**Issue by whit537** [gratipay/grtp.co#172]
Currently deployment is in some kinda state. My local git repo is out of sync with prod. I don't have time to debug right now, and #171 may be the answer anyway. Flagging in a ticket for now.

**Comment by techtonik** [comment]
@whit537 hi, is there any progress with deployment on your side? At least would be nice to see errors.

**Comment by whit537** [comment]
Sadly no. I'm deep into https://github.com/gratipay/inside.gratipay.com/issues/948 right now and am not seeing this as a priority unfortunately. Maybe you can convince @rohitpaulk or @clone1018 to work on this sooner than I'll be able to get to it? 😞

**Comment by rohitpaulk** [comment]
Hmm, why aren't we just hosting this on Heroku :/ Costs?

**Comment by rohitpaulk** [comment]
I'd be okay with working on getting this hosted on Heroku, so that we never have to deal with it again :)

Heroku is a provider we trust, all our other apps are hosted there, and they have the features required to host this app. I don't see a reason to involve another provider other than the cost, which would be just $7/month in case of Heroku

**Comment by mattbk** [comment]
Where is it hosted now?

**Comment by clone1018** [comment]
A DigitalOcean droplet

**Comment by techtonik** [comment]
Diversification is good. Alternative platforms for some services helps code to be more universal. Just need somebody with DigitalOcean access to push the changes.

**Comment by whit537** [comment]
+1 for Heroku

**Comment by whit537** [comment]
While I agree in principle that diversification is good and that portability generally improves code, I think at this stage of the game agility is more important. By standardizing on Heroku we reduce mental overhead and we can move faster. +1 for Heroku.

**Comment by clone1018** [comment]
If we move this to Heroku we get insta-ssl also without any .well-known craziness.

**Comment by mattbk** [comment]
I have no problem with it (although https://github.com/gratipay/grtp.co/issues/163#issue-206822864 still stands).

**Comment by clone1018** [comment]
I've been messing around on heroku to get grtp potentially moved over and it was very simple.

The setup was essentially just specifying two buildpacks in the heroku config:
1. index=1 heroku/nodejs
2. index=2 https://github.com/heroku/heroku-buildpack-static.git

And adding a `postinstall` of `make build`. So really what's happening is heroku is installing nodejs for the build and then a simple nginx server serves up the `www/` directory

Here's a demo: 
https://grtp.herokuapp.com/v2.js

Deployment would be as simple as `./deploy.sh` or `git push heroku master` depending on how we want it.

**Comment by techtonik** [comment]
There are two important issues beyond Heroku that don't allow me to do changes:

1. https://github.com/gratipay/grtp.co/issues/170
2. unable to upgrade Grunt https://github.com/gratipay/grtp.co/issues/107#issuecomment-297047239

**Comment by clone1018** [comment]
I think we should try simplifying the stack. JavaScript has changed a lot since grtp started. What alternatives are there for testing now @techtonik ? Should we be using a simpler gulp process or webpack also?

**Comment by techtonik** [comment]
@clone1018 I have almost no idea about what is happening on JavaScript world. @rummik should now better.

**Comment by techtonik** [comment]
Moved to Heroku in https://github.com/gratipay/grtp.co/pull/173 Deployment now works - https://grtp.co/v2.js
