### ISSUE TITLE
Change DNS

### ISSUE THREAD

**Issue by clone1018** [gratipay/grtp.co#174]
Here's the proven test of our new grtp.co host: https://jsfiddle.net/0wc0vrzy/

And here are the required DNS changes:

![image](https://cloud.githubusercontent.com/assets/226638/25829120/f14f9cbe-3419-11e7-9afd-727cee4efb16.png)

**Comment by whit537** [comment]
Decided IRL to scrap `www`.

**Comment by whit537** [comment]
Still, we need to move this from iwantmyname to dnsimple in order to use an `ALIAS` record.

**Comment by whit537** [comment]
Alright, I just switched nameservers to dnsimple.

**Comment by whit537** [comment]
Done!

![screen shot 2017-05-09 at 9 51 41 am](https://cloud.githubusercontent.com/assets/134455/25856936/20471ae6-349d-11e7-886d-f34f0bd275d5.png)
