### ISSUE TITLE
Choose testing framework for Widgets/API

### ISSUE THREAD

**Issue by techtonik** [gratipay/grtp.co#176]
DalekJS is dead. It prevents `grunt` and dependencies from upgrading. It also incomplete leaving these issues:

1. location of test server is hardcoded into test itself
2. there is no test discovery in `dalek-cli` - every test suite (.js file) should be passed explicitly

So we need another framework to testing grtp.co. Any recommendation, rationale, preferences?

It should be easy to install and run tests with single `npm` invocation - without manually instaling Selenium .jar and other prerequisites.

**Comment by mattbk** [comment]
https://gratipay.com/Distilled/ ?

**Comment by techtonik** [comment]
@mattbk asked if Distilled can help - https://gitlab.com/distilled/distilled/issues/13

**Comment by techtonik** [comment]
It appears that JavaScript testing frameworks are actually a bunch of different components, which are not organized in any pipeline, so to understand this ecosystem, there should be a picture of that pipeline:

    [ discovery ] --> [ execution ] --> [ reporting ]

                  --> [ unit test ]
    [ execution ] --> [ browser test ]

                         1. [ server control ]
    [ browser test ] --> 2. [ browser control ]
                         3. [ test executor ]

DalekJS doesn't do `[ discovery ]` and `[ server control ]`. Discovery is now made by `grunt` (scanning `test/**/*.js`, and  `[ server control ]` is made by `grunt-contrib-connect`.

Still trying to figure out what are Distilled roles here.

**Comment by techtonik** [comment]
Need to make a diagram for it. Later.

![image](https://cloud.githubusercontent.com/assets/515889/26025770/6854ae4a-37f7-11e7-9ff3-2eae843ba737.png)

http://interactive.blockdiag.com/?compression=deflate&src=eJxLyslPzk7JTExXqOZSUEjJLE7OL0stqlTQtVNIrUhNLi3JzM8DcYpSC_KLSjLz0q25agHiGBIk

**Comment by mattbk** [comment]
Some great explanations over at https://gitlab.com/distilled/distilled/issues/13.

**Comment by techtonik** [comment]
Reading pretty fresh review - https://spin.atomicobject.com/2017/05/02/react-testing-jest-vs-mocha/
