### ISSUE TITLE
Change license

### ISSUE THREAD

**Issue by mattbk** [gratipay/grtp.co#177]
https://github.com/gratipay/grtp.co/blob/master/COPYING is CC0 right now. According to [Creative Commons](https://creativecommons.org/faq/#can-i-apply-a-creative-commons-license-to-software), we should use a software license instead.

**Comment by whit537** [comment]
This is a pre-req for getting closer with [OSI](https://opensource.org/) as well, since CC0 is [not actually OSI-approved](https://opensource.org/faq#cc-zero). We're not actually open source! 😱

**Comment by mattbk** [comment]
Which of these should we use? https://opensource.org/licenses

Gratipay.com is CC0 right now, too: https://github.com/gratipay/gratipay.com/blob/master/COPYING.

**Comment by whit537** [comment]
I've been nervous about bringing this up, because licensing discussions are a bikeshed. We're using MIT   fooooorrrrrrrr ... ooooooo, [no we're not](https://github.com/gratipay/postgres.py/issues/12). 😳

**Comment by techtonik** [comment]
UNLICENSE is a proper replacement.

**Comment by techtonik** [comment]
I mean that people should have the right to opt-out of all rules that we are not subscribed to. I don't want to play on the same field that copyright lawyers do - I just want to opt-out of its restrictions and regulations, and if you accept any kind of license, you're automatically dragged underwater. UNLICENSE is the best choice to state my position to release code into wild for free with no strings attached,

**Comment by whit537** [comment]
Like I said. 😞

**Comment by techtonik** [comment]
At least CC-0 is GPL-compatible. https://wiki.creativecommons.org/wiki/CC0_FAQ#May_I_apply_CC0_to_computer_software.3F_If_so.2C_is_there_a_recommended_implementation.3F

**Comment by techtonik** [comment]
Damm't. I want to copy/paste code without all this legal bullshiiit. :sob:
