### ISSUE TITLE
Expose how many people are supporting someone

### ISSUE THREAD

**Issue by techtonik** [gratipay/grtp.co#76]
People don't have time to follow, but they want to give their support to certain people. The $ value is not an indicator of popularity, but a number of supporters is.

**Comment by rohitpaulk** [comment]
The number of supporters is shown on a graph for every user. Doesn't that serve the purpose?

**Comment by colindean** [comment]
Ooo I like that idea a lot. Let the user choose, perhaps even animate a switch between the two figures.

**Comment by techtonik** [comment]
@rohitpaulk it is not exposed through widgets from what I can see.

**Comment by rohitpaulk** [comment]
Yep, true - it's not on the widgets.

**Comment by rummik** [comment]
It's not exposed as a class to the widgets, but it's exposed in the public.json on Gratipay (see https://gratipay.com/rummik/public.json)

Adding `text('patrons', data.npatrons);` around [lib/v1/api.js#L131](https://github.com/gratipay/grtp.co/blob/master/lib/v1/api.js#L131) should cover it
