### ISSUE TITLE
Blogger Gadget

### ISSUE THREAD

**Issue by techtonik** [gratipay/grtp.co#78]
Ouch. I created a branch, but didn't checked it out before commit, so the change is already in `master`.

**Comment by techtonik** [comment]
The commit for review is https://github.com/gratipay/grtp.co/commit/6ec99b1756d8332e70f238a9a91c7c42217a3587.

**Comment by whit537** [comment]
I've gone ahead and force-pushed your commit off master, so you can go ahead and open a PR. :-)

**Comment by techtonik** [comment]
Thanks. =) Now I need to remember how to move this commit to a different branch.

**Comment by techtonik** [comment]
Submitte PR #79, ready to review.
