### ISSUE TITLE
Release/Deploy 0.1.3

### ISSUE THREAD

**Issue by techtonik** [gratipay/grtp.co#83]
I don't have access to deploy code as described in https://github.com/gratipay/grtp.co#deployment

It looks like this also needs a version bump.

**Comment by whit537** [comment]
@rummik?

**Comment by rummik** [comment]
I'll have this done this afternoon.  Meant to do it last night, but NPM decided to take forever for some reason.

**Comment by techtonik** [comment]
http://grtp.co/v1/ is still hanging at the old version. Is there some problem we can help with?

**Comment by rummik** [comment]
The only problem is me >.>;  I'm super forgetful.

**Comment by rummik** [comment]
Deployed now

**Comment by techtonik** [comment]
Happens to me every time.

http://grtp.co/v1/blogger/gratipay.xml is not there. Is the problem that files in `lib/` need to be `compiled`?

**Comment by rummik** [comment]
Things in `lib/` get minified to `www/`

**Comment by techtonik** [comment]
Finally understood how does it work. Pull request #91 fixes missing Blogger widget. Hook script on server side might need to be updated. It worth to add it to version control `other/` or `scripts/` directory together with nginx config in #88.

**Comment by techtonik** [comment]
I can try to deploy, but I need access to grtp.co host https://launchpad.net/~techtonik/+sshkeys

**Comment by techtonik** [comment]
Need to go wrap another release. Because 0.1.3 is already tagged and deployed. !m @rummik

**Comment by whit537** [comment]
> I can try to deploy, but I need access to grtp.co host https://launchpad.net/~techtonik/+sshkeys

Try `ssh root@grtp.co` using your first key.

**Comment by techtonik** [comment]
That works. Thanks.

**Comment by whit537** [comment]
Yay! :)
