### ISSUE TITLE
Measure popularity of the widgets

### ISSUE THREAD

**Issue by techtonik** [gratipay/grtp.co#87]
Public information about how popular certain widgets/gadgets are, will be interesting for people to evaluate which platforms are more useful, which gadgets are more pleasing to people.

This will even allow to create widget design/popularity contest.

**Comment by rummik** [comment]
We have NGINX logs on the server, so we can just pull out the URLs and go from there

**Comment by techtonik** [comment]
Cool. There is a plenty of options -  https://www.google.com/#q=nginx+log+analyzer Need to:
 * [ ] understand what is the stored log period
 * [ ] how to run aggregation task daily
 * [ ] store aggregated stats and
 * [ ] show them

**Comment by mattbk** [comment]
This would be useful to have in order to determine when we can retire `v1` widgets (https://github.com/gratipay/grtp.co/issues/103#issuecomment-215236272).
