### ISSUE TITLE
Commit nginx config

### ISSUE THREAD

**Issue by techtonik** [gratipay/grtp.co#88]
I need `nginx` config to setup reproducible environment on my machine. @rummik @seanlinsley @whit537 - can you commit the config or link here, so I can commit it myself.

**Comment by techtonik** [comment]
What is the best name for directory that will contain supporting files, such as nginx config and git post-receive hook script?

**Comment by whit537** [comment]
Maybe `config`?

**Comment by whit537** [comment]
Looks like in #95 we're going with `infra`.

!m @techtonik

**Comment by techtonik** [comment]
Thanks for review. ;)
