### ISSUE TITLE
Test and announce Blogger support

### ISSUE THREAD

**Issue by techtonik** [gratipay/grtp.co#94]
0.1.4 is live and it is now safe to announce Blogger gadgets support.

**Comment by whit537** [comment]
Where do we document this? What should our tweet say? Where should it link to?

**Comment by techtonik** [comment]
It is documented here https://github.com/gratipay/grtp.co/tree/master/lib/v1/blogger with a link from README.md. Tweet could say "Our old good widget ported to Blogger. Please test how it works for you and send your enhancements to https://github.com/gratipay/grtp.co/tree/master/lib/v1/blogger

**Comment by techtonik** [comment]
I need to receive feedback to ensure that everything is ok, but I am not sure where to handle it. The tracker looks better place than anything else.

**Comment by whit537** [comment]
Waiting for #97.

**Comment by whit537** [comment]
We should document this on the Widgets page on the main site and link to that instead of the README in GitHub.

**Comment by techtonik** [comment]
Yes. The Widgets page.. The Widgets page should be maintained in grtp.co repository, because three places to sync that info - README.md examples, grtp.co site and gratipay.com site is too much.

I'd move all that widgets info to grtp.co frontpage. Right now it is unusable, but should be somthing like https://shields.io

**Comment by whit537** [comment]
> I'd move all that widgets info to grtp.co frontpage.

@techtonik That's a fine idea, reticketed as #98. I don't think we should block this on that, though. :)

**Comment by techtonik** [comment]
#98 will solve the issue (and I am not using Blogger widget anymore as there is no income).
