### ISSUE TITLE
migrate Widgets to grtp.co homepage

### ISSUE THREAD

**Issue by whit537** [gratipay/grtp.co#98]
Reticketed from https://github.com/gratipay/grtp.co/issues/94#issuecomment-88810310.

We can link to grtp.co from gratipay.com with a `?username=foo` or whatevs to contextualize it for authenticated users.

**Comment by techtonik** [comment]
This issue is about making https://grtp.co/ similar to https://shields.io/ with demo of available API and widgets (including Blogger and channel to report issues) and less text.

**Comment by mattbk** [comment]
How does this jive or not with @whit537's thoughts at https://github.com/gratipay/grtp.co/issues/103#issuecomment-229479424?

I'd still like to take a step back and maybe consider widgets as a way to get people to give money, and use Shields for the reporting side.

**Comment by techtonik** [comment]
I think it is only logical to concentrate on API and let people design and host their own widgets including Shields. But we need to show examples how to do this, because this task is non-trivial.
